name: Build, Test and Deploy

on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
 workflow_dispatch:

jobs:
 npm-security-tests:
  runs-on: ubuntu-latest

  steps:
  - name: Copy the repo
    uses: actions/checkout@v4
  - name: Use Node.js 20.x
    uses: actions/setup-node@v4
    with:
      node-version: 20.x
      cache: 'npm'
  - name: Start Audit script
    run: npm run sec-test-npm